version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4

references:
  workspace_root: &workspace_root /tmp/workspace

executors:
  main-executor:
    docker:
      - image: circleci/node:10.19.0
        environment:
          TZ: 'America/New_York'
          NODE_OPTIONS: '--max_old_space_size=4096'
          GATSBY_CPU_COUNT: 2
    working_directory: *workspace_root

jobs:
  api:
    executor: main-executor
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: fetch-api-repo
          command: 'npm run setup:api-repo'
      - run:
          name: fetch-data-repo
          command: 'npm run setup:data-repo'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - _api
            - _data
  gatsby-build:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: install
          command: 'npm install'
      - run:
          name: setup
          command: 'npm run setup:env-vars'
      - run:
          name: scrollama
          command: 'npm run build:scrollama'
      - run:
          name: build
          command: 'npm run build:gatsby'
      - run:
          name: test
          command: 'npm run build:test'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - _api
            - _data
            - public
  gatsby-test:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: install
          command: 'npm install'
      - run:
          name: test
          command: 'npm run test:coverage'
      - coveralls/upload:
        path_to_lcov: './junit.xml'
  gatsby-lint:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: install
          command: 'npm install'
      - run:
          name: scrollama
          command: 'npm run build:scrollama'
      - run:
          name: lint
          command: 'npm run test:lint'
  storybook:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: install
          command: 'npm install'
      - run:
          name: storybook
          command: 'npm run storybook:build'
workflows:
  version: 2
  build_and_test:
    jobs:
      - api
      - gatsby-build:
          requires:
            - api
      - gatsby-lint:
          requires:
            - api
      - gatsby-test:
          requires:
            - api
      - storybook:
          requires:
            - api
